name: 'urVault action'
description: ''
inputs:
  baseurl: 
    description: ''
    required: true
    default: null  
  token: 
    description: ''
    required: true
    default: null
  id: 
    description: ''
    required: true
    default: null
  type: 
    description: ''
    required: true
    default: dotenv
  filename: 
    description: ''
    required: true
    default: null
    
    
runs:
  using: "composite"
  steps:
    - name: Download env
      shell: bash
      run: |
        curl --location "${{ inputs.baseurl }}/v1/vwt/${{ inputs.id }}?type=${{ inputs.type }}" --header "x-api-token: ${{ inputs.token }}" -o ${{ inputs.filename || inputs.id }}
    - run: ls -lah
      shell: bash
    - name: Set Environment Variables
      shell: bash
      id: set-env
      run: |
        curl --location "${{ inputs.baseurl }}/v1/vwt/${{ inputs.id }}?type=dotenv" --header "x-api-token: ${{ inputs.token }}" -o .tmp.env
        while IFS= read -r line || [[ -n "$line" ]]; do
          # Extract variable name and value
          var_name=$(echo "$line" | cut -d '=' -f 1)
          var_value=$(echo "$line" | cut -d '=' -f 2-)
          
          # Set the variable in $GITHUB_ENV
          echo "$var_name=$var_value" >> $GITHUB_ENV
          
          # Add mask for sensitive variables
          echo "::add-mask::$var_value"
        done < .tmp.env
        rm .tmp.env
